import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/component/shared/Navbar";
import Footer from "@/component/Footer/Footer";
import FriendList from "@/component/FriendCart/FriendList";
import Banner from "@/component/banner/Banner";



const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "KeenKeeper",
  description: "Generated by KeenKeeper",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <Navbar></Navbar>
        
        <main className="container mx-auto">
          {children}
        </main>

        <Banner></Banner>
      {/* <FriendList></FriendList> */}

       <Footer></Footer>
        </body>
    </html>
  );
}
