import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/component/shared/Navbar";
import Footer from "@/component/Footer/Footer";
import FriendList from "@/component/FriendCart/FriendList";
import Banner from "@/component/banner/Banner";
import FinalFriendCart from "@/component/FriendCart/FinalFriendCart";
import ThisdataCart from "@/component/FriendCart/ThisdataCart";
// import { Toaster } from "react-hot-toast";
import { ToastContainer } from "react-toastify";



const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "KeenKeeper",
  description: "Generated by KeenKeeper",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <Navbar></Navbar>
        
        {/* <Toaster position="top-center" /> */}
        <main className="container mx-auto">
          {children}
       
        </main>
    <ToastContainer />
        <Banner></Banner>

        <ThisdataCart></ThisdataCart>
      {/* <FriendList></FriendList> */}
      

       <Footer></Footer>
        </body>
    </html>
  );
}
